# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param n the parameter of binomial 
#' @param a shape1 of beta function
#' @param b shape2 of beta function
#' @param N the number of markov chain
#' @param x1 the initial value of x
#' @param y1 the initial value of y
#' @return a markov chain
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(n, a, b, N, x1, y1) {
    .Call('_StatComp21084_gibbsC', PACKAGE = 'StatComp21084', n, a, b, N, x1, y1)
}

